MafiaBoardGame/UI/Controllers/PartieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Domain.Dto;
using UI.Models;
using System.Text;
using System.Web.UI;

namespace UI.Controllers
{

    public class PartieController : Controller
    {
        private readonly int LANCER_PARTIE_TIMER_INTERVAL = 15;
        string status;
        //infos timer : https://msdn.microsoft.com/en-us/library/system.timers.timer.elapsed%28v=vs.110%29.aspx


        //signature spécifique pour correspondre au delegate du ElapsedEventHandler
        private void TimerLancerPartieEcoule(object sender, EventArgs e)
        {
            LancerPartie();
        }

        // GET: Partie
        public ActionResult Index()
        {
            if (Session["user"] == null)
                return RedirectToAction("Index", new { controller = "Index" });

            ViewData["username"] = ((JoueurDto)Session["user"]).Pseudo;
            return View();
        }

        public ActionResult Creer()
        {
            return PartialView("CreerForm");
        }

        [HttpPost]
        public ActionResult Creer(string nomPartie)
        {
            string pseudo = ((JoueurDto)Session["user"]).Pseudo;
            PartieDto part = UCCPartie.Instance.CreerPartie(nomPartie, pseudo);
            if (part != null)
            {
                Session["partie"] = part.Id;
                Session.Add("partieCreation", DateTime.Now);
                return RedirectToAction("WaitForStart", part);
            }
            else
            {
                TempData["error"] = "Un problème est servenu lors de la création de la partie";
                return RedirectToAction("Creer");
            }
        }

        public void LancerPartie()
        {
            int idPartie = (int)Session["partie"];
            int NbJoueurs = UCCPartie.Instance.getListJoueurParticipantsDto(idPartie).Length;
            /*if (NbJoueurs == 1)
            {
                UCCPartie.Instance.annuler(idPartie);
                TempData["error"] = "Pas assez de joueurs. Partie annulée.";
                RedirectToAction("Index");
                return;
            }*/
            PartieDto p;
            if (NbJoueurs > 1)
            {
                p = UCCPartie.Instance.LancerPartie();
                if (p == null)
                    TempData["statut"] = "pasGo";
                else
                    TempData["statut"] = "go";
                return;
            }
            /*  if (p == null)
              {
                  TempData["error"] = "Un problème est servenu lors du lancement de la partie";
                  RedirectToAction("Index");
                  return;
              }*/

            //return RedirectToAction("Index", "Plateau", p.Nom);
        }

        public ViewResult WaitForStart(PartieDto partie)
        {
            LoadScreenModel model = new LoadScreenModel();
            model.Partie = partie;
            model.Participants = UCCPartie.Instance.getListJoueurParticipantsDto(partie.Id).ToList();
            return View(model);
        }


        public PartialViewResult RefreshLoadScreen()
        {
            TempData["statut"] = "pasGo";
            int idPartie = (int)Session["partie"];
            if (Session["partieCreation"] != null)
            {
                //DateTime partieCreation = (DateTime)Session["partieCreation"];
                //TimeSpan ts = DateTime.Now.Subtract(partieCreation);

                LancerPartie();
                Session.Remove("partieCreation");
                //status = "coucou";

            }
            else {
                if (UCCPartie.Instance.getGameState(((JoueurDto)Session["user"]).Pseudo).Etat != (int)ETAT_PARTIE.INSCRIPTION)
                {
                    TempData["statut"] = "go";
                }
            }


            return PartialView(UCCPartie.Instance.getListJoueurParticipantsDto(idPartie).ToList());
        }

        public ActionResult Rejoindre()
        {
            JoueurDto j = (JoueurDto)Session["user"];
            PartieDto p = UCCPartie.Instance.RejoindrePartie(j.Pseudo);
            if (p != null)
            {
                Session["partie"] = p.Id;
                return RedirectToAction("WaitForStart", p);
            }
            else
            {
                TempData["error"] = "Impossible de rejoindre la partie en cours";
                return RedirectToAction("Index");
            }
        }


        public ActionResult VoirPartiesJouees()
        {
            JoueurDto j = (JoueurDto)Session["user"];
            List<PartieDto> parties = UCCPartie.Instance.VoirPartie(j.Pseudo).ToList();
            if (parties == null)
            {
                parties = new List<PartieDto>();
            }
            return PartialView("VoirPartiesJouees", parties);
        }

    }

}

MafiaBoardGame/UI/Views/Partie/CreerForm.cshtml
<h3>
    Créer partie
</h3>

@using (Html.BeginForm("Creer", "Partie", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Nom partie")
        @Html.TextBox("nomPartie", "", new { @class = "form - control" })
    </div>
    <input type="submit" value="Creer Partie" class="btn btn-primary" />
}

MafiaBoardGame/UI/Views/Partie/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Your Account";
}

<h2>Mafia Game Board</h2>
<h3>Bienvenue @ViewData["username"]</h3>
<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="javascript:showCreer()"> Créer partie </a>
                </li>
                <li>
                    @Html.ActionLink("Rejoindre une partie", "Rejoindre", new { controller = "Partie" })
                </li>
                <li>
                    <a href="javascript:showVoirPartiesJouees()"> Voir Parties Jouees</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div id="Creer">
    @{Html.RenderAction("Creer", new { controller = "Partie" });}
</div>

<div id="VoirPartiesJouees" style="display:none;">
    @{Html.RenderAction("VoirPartiesJouees", new { controller = "Partie" });}
</div>

<script type="text/javascript">
    function showCreer() {
        $('#VoirPartiesJouees').hide();
        $('#VoirPartiesDisponibles').hide();
        $('#Creer').show();
    }

    function showVoirPartiesJouees() {
        $('#Creer').hide();
        $('#VoirPartiesDisponibles').hide();
        $('#VoirPartiesJouees').show();
    }
</script>

MafiaBoardGame/UI/Views/Partie/RefreshLoadScreen.cshtml
@model List<Domain.Dto.JoueurPartieDto>

<h3>
    Joueurs inscrits :
</h3>
    <ul>
        @foreach (var jp in Model)
        {
            <li>@jp.Joueur.Pseudo</li>
        }
    </ul>

    En attente d'autres joueurs...


<i id="status" style="display:none" data-status="@(TempData["statut"])"></i>

MafiaBoardGame/UI/Views/Partie/VoirParties.cshtml
@model List<Domain.Dto.PartieDto>
@{
    //TODO ajouter un viewmodel
}
<h3>
    Parties jouées
</h3>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Nom
            </th>
            <th>
                Date
            </th>
            <th>
                Vainqueur
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model)
        {
            <tr>
                <td>
                    @p.Nom
                </td>
                <td>
                    @p.DateHeureCreation.Hour : @p.DateHeureCreation.Minute @p.DateHeureCreation.Day / @p.DateHeureCreation.Month / @p.DateHeureCreation.Year
                </td>
                <td>
                    @p.Vainqueur.Pseudo
                </td>
            </tr>
        }
    </tbody>
</table>

MafiaBoardGame/UI/Views/Partie/VoirPartiesJouees.cshtml
@model List<Domain.Dto.PartieDto>

<h3>
    Parties jouées
</h3>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Nom
            </th>
            <th>
                Date
            </th>
            <th>
                Vainqueur
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model)
        {
            <tr>
                <td>
                    @p.Nom
                </td>
                <td>
                    @p.DateHeureCreation.Hour : @p.DateHeureCreation.Minute @p.DateHeureCreation.Day / @p.DateHeureCreation.Month / @p.DateHeureCreation.Year
                </td>

                @if (@p.Vainqueur != null)
                {
                    <td>
                        @p.Vainqueur.Pseudo
                    </td>
                }
                else
                {
                    <td>
                        Pas de vainqueur
                    </td>
                }

            </tr>
        }
    </tbody>
</table>

MafiaBoardGame/UI/Views/Partie/WaitForStart.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "En attente des joueurs";
}

@model UI.Models.LoadScreenModel

<h2>
    Nouvelle partie - @Model.Partie.Nom - @(TempData["statut"])

</h2>
<div id="infos">
    @{
    Html.RenderPartial("RefreshLoadScreen", Model.Participants);
    }
</div>

<script>
    $(document).ready(function () {
        setInterval(function () {
            $('#infos').load('/Partie/RefreshLoadScreen');
            var status = $('#status').attr('data-status');

            if (status === "go") {
                location.href = '/Plateau/Index';
            }

        }, 10000);
    });
</script>