MafiaBoardGame/UI/Controllers/JoueurController.cs
using Domain.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Controllers;
using UI.Models;

namespace UI.Controllers
{
    public class JoueurController : Controller
    {

        public void Session_OnEnd()
        {
            throw new Exception("Session timed OUT !");
        }

        [HttpPost]
        public ActionResult LogIn(string pseudo, string mdp)
        {
            JoueurDto jDto = UCCJoueur.Instance.ConnexionJoueur(pseudo, mdp);

            if (jDto == null)
            {
                TempData["error"] = "Erreur de login ou mot de passe";
                return RedirectToAction("Index", new { controller = "Index" });
            }

            Session.Add("user",jDto);
            Session.Timeout = 40;

            return RedirectToAction("Index", "Partie");
        }

        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();
            return RedirectToAction("Index", new { controller = "Index" });
        }

        public ViewResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserModel j)
        {
            bool res = UCCJoueur.Instance.InscriptionJoueur(j.Pseudo, j.Mdp);
            if (!res)
            {
                ViewData["errorMessage"] = "Erreur lors de l'inscription du joueur";
                return View();
            }
            else {
                return RedirectToAction("ConfirmRegistration");
            }
        }

        public ViewResult ConfirmRegistration()
        {
            return View();
        }
    }
}

MafiaBoardGame/UI/Views/Index/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model UI.Models.UserModel

@{
    ViewBag.Title = "Welcome";
    //TODO ajouter un lien vers l'écran d'enregistrement d'utilisateur
}
<div class="panel">
    <div class="panel-heading">
        <h2>Mafia Board Game - Connexion</h2>
    </div>
    <div class="panel-body">
        @if (TempData["error"] != null)
        {
        <div class="alert alert-danger">
            @TempData["error"]
        </div>
        }

        @using (Html.BeginForm("LogIn", "Joueur", FormMethod.Post))
        {
        <div class="form-group">
            @Html.LabelFor(m => Model.Pseudo, "Nom d'utilisateur")
            @Html.TextBoxFor(m => Model.Pseudo, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => Model.Mdp, "Mot de passe")
            @Html.PasswordFor(m => Model.Mdp, new { @class = "form-control" })
        </div>
        <br />
        <input type="submit" value="Se connecter" class="btn btn-primary" />
        }
        <div>
            Pas encore de compte ?
            @Html.ActionLink("Créer un compte", "Register", new { controller = "Joueur" }, new { @class = "" })

        </div>

    </div>
</div>